name: Deploy Micro Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create bundles directory
        run: |
          mkdir -p micro-apps/bundles

      - name: Install Dependencies
        run: |
          cd micro-apps
          npm install

      - name: Build Micro Apps
        env:
          BUNDLE_BASE_URL: https://xerophilus.github.io
          REPO_NAME: super-app-template
        run: |
          cd micro-apps
          # Build all micro-apps
          npm run build-all
          
          # Move manifest files to root of bundles directory
          echo "Moving manifest files to root of bundles directory..."
          cp bundles/manifest.json bundles/manifest.json.tmp
          cp bundles/public-manifest.json bundles/public-manifest.json.tmp
          cp bundles/protected-manifest.json bundles/protected-manifest.json.tmp
          
          # Move manifest files back
          mv bundles/manifest.json.tmp bundles/manifest.json
          mv bundles/public-manifest.json.tmp bundles/public-manifest.json
          mv bundles/protected-manifest.json.tmp bundles/protected-manifest.json
          
          # Verify deployment files
          echo "=== Contents of bundles directory ==="
          ls -la bundles
          
          echo "=== Verifying manifest files ==="
          for manifest in manifest.json public-manifest.json protected-manifest.json; do
            if [ -f "bundles/$manifest" ]; then
              echo "✓ Found $manifest"
              echo "Content of $manifest:"
              cat "bundles/$manifest"
              echo "---"
            else
              echo "✗ Missing $manifest"
              exit 1
            fi
          done
          
          echo "=== Verifying bundle files ==="
          expected_bundles=(
            "micro-app-one/bundle.js"
            "micro-app-two/bundle.js"
            "micro-app-three/bundle.js"
          )
          
          for bundle in "${expected_bundles[@]}"; do
            if [ -f "bundles/$bundle" ]; then
              echo "✓ Found $bundle ($(wc -c < "bundles/$bundle") bytes)"
            else
              echo "✗ Missing $bundle"
              exit 1
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: micro-apps/bundles

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 