name: Deploy Micro Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create bundles directory
        run: |
          mkdir -p micro-apps/bundles

      - name: Install Dependencies
        run: |
          cd micro-apps
          npm install

      - name: Build Micro Apps
        env:
          BUNDLE_BASE_URL: https://xerophilus.github.io
          REPO_NAME: super-app-template
        run: |
          cd micro-apps
          # Build all micro-apps
          npm run build-all
          
          # Rename bundle files to their final names
          find bundles -type f -name "bundle.js" | while read file; do
            dir=$(dirname "$file")
            app=$(basename "$dir")
            mv "$file" "bundles/$app.bundle.js"
          done
          
          # Clean up empty directories
          find bundles -type d -empty -delete
          
          # Verify deployment files
          echo "=== Contents of bundles directory ==="
          ls -la bundles
          
          echo "=== Verifying manifest files ==="
          for manifest in manifest.json public-manifest.json protected-manifest.json; do
            if [ -f "bundles/$manifest" ]; then
              echo "✓ Found $manifest"
              echo "Content of $manifest:"
              cat "bundles/$manifest"
              echo "---"
            else
              echo "✗ Missing $manifest"
              exit 1
            fi
          done
          
          echo "=== Verifying bundle files ==="
          for bundle in bundles/*.bundle.js; do
            if [ -f "$bundle" ]; then
              echo "✓ Found $(basename "$bundle")"
            fi
          done

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: micro-apps/bundles

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 