name: Deploy Micro Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create bundles directory
        run: |
          mkdir -p micro-apps/bundles

      - name: Install Dependencies
        run: |
          cd micro-apps
          npm install

      - name: Build Micro Apps
        env:
          BUNDLE_BASE_URL: https://xerophilus.github.io
          REPO_NAME: super-app-template
        run: |
          cd micro-apps
          npm run build-all
          # Move bundles to their final locations
          for app in micro-app-*; do
            if [ -f "bundles/$app/bundle.js" ]; then
              mv "bundles/$app/bundle.js" "bundles/$app.bundle.js"
            fi
          done
          # Clean up empty directories
          rm -rf bundles/micro-app-*
          # List contents for verification
          echo "Contents of bundles directory:"
          ls -la bundles
          echo "Manifest content:"
          cat bundles/manifest.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: micro-apps/bundles

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 