name: Deploy Micro Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create bundles directory
        run: |
          mkdir -p micro-apps/bundles/micro-app-one
          mkdir -p micro-apps/bundles/micro-app-two
          mkdir -p micro-apps/bundles/micro-app-three

      - name: Install Dependencies
        run: |
          cd micro-apps
          npm install

      - name: Build Micro Apps
        env:
          BUNDLE_BASE_URL: https://xerophilus.github.io
          REPO_NAME: super-app-template
        run: |
          cd micro-apps
          npm run build-all
          ls -la bundles
          ls -la bundles/micro-app-one || true
          ls -la bundles/micro-app-two || true
          ls -la bundles/micro-app-three || true
          cat manifest.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: micro-apps/bundles

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 